### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not _io.BufferedReader

### ISSUE THREAD

**Issue by Reversev** [OpenDriveLab/UniAD#190]
I want to eval these models, but some error was happened as fellow:

Traceback (most recent call last):
  File "/anaconda3/envs/py38/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/UniAD/projects/mmdet3d_plugin/datasets/nuscenes_e2e_dataset.py", line 78, in __init__
    super().__init__(*args, **kwargs)
  File "/UniAD/mmdetection3d/mmdet3d/datasets/nuscenes_dataset.py", line 131, in __init__
    super().__init__(
  File "/UniAD/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 88, in __init__
    self.data_infos = self.load_annotations(open(local_path, 'rb'))
  File "/UniAD/projects/mmdet3d_plugin/datasets/nuscenes_e2e_dataset.py", line 152, in load_annotations
    data = pickle.loads(self.file_client.get(ann_file))
  File "/anaconda3/envs/py38/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 1015, in get
    return self.client.get(filepath)
  File "/anaconda3/envs/py38/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 536, in get
    with open(filepath, 'rb') as f:
TypeError: expected str, bytes or os.PathLike object, not _io.BufferedReader

Can you help me?

**Comment by Reversev** [comment]
input command: ```bash ./tools/uniad_dist_eval.sh ./projects/configs/stage1_track_map/base_track_map.py ./ckpts/uniad_base_track_map.pth 1```

**Comment by YTEP-ZHI** [comment]
You should use the **full test dataset**, not mini, for evaluation.

**Comment by OrangeSodahub** [comment]
@Reversev Nah, Nah, to solve the problme you should check the `NuScenesDataset.classes_names` is type of `list` or `dict.__keys__`, in your case, it should be a list, but is `dict.__keys__`.
