### ISSUE TITLE
how to eval on 1 gpu ?

### ISSUE THREAD

**Issue by XiaoJiNu** [OpenDriveLab/UniAD#41]
Hi, what parameters I should modify when I only have one gpu ? I don't want to train but to eval our model.

I modified ./tools/uniad_dist_eval.sh as following but occurs bug that KeyError: 'RANK' in File "./tools/test.py", line 184, in main
init_dist(args.launcher, **cfg.dist_params)

            #!/usr/bin/env bash
            
            T=`date +%m%d%H%M`
            
            # -------------------------------------------------- #
            # Usually you only need to customize these variables #
            CFG=$1                                               #
            CKPT=$2                                              #
            # -------------------------------------------------- #
            GPUS_PER_NODE=1
            
            MASTER_PORT=${MASTER_PORT:-28596}
            WORK_DIR=$(echo ${CFG%.*} | sed -e "s/configs/work_dirs/g")/
            # Intermediate files and logs will be saved to UniAD/projects/work_dirs/
            
            if [ ! -d ${WORK_DIR}logs ]; then
                mkdir -p ${WORK_DIR}logs
            fi
            
            PYTHONPATH="$(dirname $0)/..":$PYTHONPATH \
            python $(dirname "$0")/test.py \
                $CFG \
                $CKPT \
                --launcher pytorch ${@:3} \
                --eval bbox \
                --show-dir ${WORK_DIR} \
                2>&1 | tee ${WORK_DIR}logs/eval.$T

What should I do to eval on 1 gpu ?

**Comment by YTEP-ZHI** [comment]
Hi @XiaoJiNu. It seems that you removed two lines which are important to make it running:
```
--nproc_per_node=$GPUS_PER_NODE \
--master_port=$MASTER_PORT \
```

Actually, simply set the GPUS=1 would be fine without changing other variables. Command is as follows:
```
./tools/uniad_dist_eval.sh ./projects/configs/stage1_track_map/base_track_map.py ./ckpts/uniad_base_track_map.pth 1
```

**Comment by hli2020** [comment]
I think we don’t need to reply every issue, if the documentation from our side is described very clear.

**Comment by RuoyuChen10** [comment]
> Hi @XiaoJiNu. It seems that you removed two lines which are important to make it running:
> 
> ```
> --nproc_per_node=$GPUS_PER_NODE \
> --master_port=$MASTER_PORT \
> ```
> 
> Actually, simply set the GPUS=1 would be fine without changing other variables. Command is as follows:
> 
> ```
> ./tools/uniad_dist_eval.sh ./projects/configs/stage1_track_map/base_track_map.py ./ckpts/uniad_base_track_map.pth 1
> ```

I try this:

```
./tools/uniad_dist_eval.sh ./projects/configs/stage1_track_map/base_track_map.py ./ckpts/uniad_base_track_map.pth 1
```

however, the error occurred:

```
[                                ] 1/6019, 0.2 task/s, elapsed: 6s, ETA: 35444sTraceback (most recent call last):
  File "./tools/test.py", line 261, in <module>
    main()
  File "./tools/test.py", line 231, in main
    outputs = custom_multi_gpu_test(model, data_loader, args.tmpdir,
  File "/home/dayan.guan/RuoyuChen/UniAD/projects/mmdet3d_plugin/uniad/apis/test.py", line 90, in custom_multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/dayan.guan/.conda/envs/uniad/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dayan.guan/.conda/envs/uniad/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/dayan.guan/.conda/envs/uniad/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dayan.guan/RuoyuChen/UniAD/projects/mmdet3d_plugin/uniad/detectors/uniad_e2e.py", line 83, in forward
    return self.forward_test(**kwargs)
  File "/home/dayan.guan/RuoyuChen/UniAD/projects/mmdet3d_plugin/uniad/detectors/uniad_e2e.py", line 291, in forward_test
    result_track = self.simple_test_track(img, l2g_t, l2g_r_mat, img_metas, timestamp)
  File "/home/dayan.guan/RuoyuChen/UniAD/projects/mmdet3d_plugin/uniad/detectors/uniad_track.py", line 755, in simple_test_track
    frame_res = self._inference_single_frame(
  File "/home/dayan.guan/RuoyuChen/UniAD/projects/mmdet3d_plugin/uniad/detectors/uniad_track.py", line 650, in _inference_single_frame
    ref_pts = self.velo_update(
  File "/home/dayan.guan/RuoyuChen/UniAD/projects/mmdet3d_plugin/uniad/detectors/uniad_track.py", line 279, in velo_update
    g2l_r = torch.linalg.inv(l2g_r2).type(torch.float)
RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`
/home/dayan.guan/.conda/envs/uniad/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3705847) of binary: /home/dayan.guan/.conda/envs/uniad/bin/python
Traceback (most recent call last):
  File "/home/dayan.guan/.conda/envs/uniad/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dayan.guan/.conda/envs/uniad/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dayan.guan/.conda/envs/uniad/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/dayan.guan/.conda/envs/uniad/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/dayan.guan/.conda/envs/uniad/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/dayan.guan/.conda/envs/uniad/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home/dayan.guan/.conda/envs/uniad/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/dayan.guan/.conda/envs/uniad/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
         ./tools/test.py FAILED        
=======================================
Root Cause:
[0]:
  time: 2023-07-02_19:57:32
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 3705847)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
  <NO_OTHER_FAILURES>
***************************************
```

**Comment by RuoyuChen10** [comment]
I solved it. This is mainly because the memory is not enough. After increasing the memory, the problem of single card evaluation is solved.

```
                         total        used        free      shared  buff/cache   available
Mem:         128585       19646       95744        2155       13195      105510
Swap:          8191           0              8191
```

**Comment by YTEP-ZHI** [comment]
@RuoyuChen10  There's a similar issue before: https://github.com/OpenDriveLab/UniAD/issues/15. Seems that this problem only occurs on 4090.

**Comment by RuoyuChen10** [comment]
> 

May not on 4090, it's memory size.

**Comment by YTEP-ZHI** [comment]
> > 
> 
> It may not be the reason for 4090, but the system memory is not enough, at least 20G of memory is required.

Thanks for your information.

**Comment by meua** [comment]
I have encountered a similar problem https://github.com/OpenDriveLab/UniAD/issues/52, but my machine's memory is also quite large.

**Comment by 86kkd** [comment]
RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`
hello @RuoyuChen10  i got the same error but memory is still available(48G totally), could you share the detail of solving this problem

**Comment by zacharyzhang95** [comment]
I had the same problem when I was running the e2e test with one GPU (2080Ti with 22GB memory) by running the command:
```
./tools/uniad_dist_eval.sh ./projects/configs/stage2_e2e/base_e2e.py ./ckpts/uniad_base_e2e.pth 1
``` 
The log is shown below:

```
[                                                  ] 0/6019, elapsed: 0s, ETA:Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/multiprocessing/spawn.py", line 127, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
from_parent: <_io.BufferedReader name=56>
/home/zc/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 8512) of binary: /home/zc/anaconda3/envs/uniad/bin/python
Traceback (most recent call last):
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
./tools/test.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-15_15:37:52
  host      : rrg517
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 8512)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 8512
=====================================================
from_parent: <_io.BufferedReader name=52>
/home/zc/anaconda3/envs/uniad/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 14 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
``` 

I solved it with the following changes: Change 'workers_per_gpu=1' in config files **_base_e2e.py,_ _base_track_map.py_** and **_nus-3d.py_.** These files can be found in UniAD/projects/configs
