### ISSUE TITLE
_pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by meua** [OpenDriveLab/UniAD#52]
Hello, how should I solve the following problems？
```bash
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ ./tools/uniad_dist_eval.sh ./projects/configs/stage1_track_map/base_track_map.py ./ckpts/uniad_base_track_map.pth 1
projects.mmdet3d_plugin
Traceback (most recent call last):
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/jarvis/coding/pyhome/github.com/meua/UniAD/projects/mmdet3d_plugin/datasets/nuscenes_e2e_dataset.py", line 78, in __init__
    super().__init__(*args, **kwargs)
  File "/home/jarvis/coding/pyhome/github.com/meua/mmdetection3d/mmdet3d/datasets/nuscenes_dataset.py", line 129, in __init__
    super().__init__(
  File "/home/jarvis/coding/pyhome/github.com/meua/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 64, in __init__
    self.data_infos = self.load_annotations(self.ann_file)
  File "/home/jarvis/coding/pyhome/github.com/meua/UniAD/projects/mmdet3d_plugin/datasets/nuscenes_e2e_dataset.py", line 152, in load_annotations
    data = pickle.loads(self.file_client.get(ann_file))
_pickle.UnpicklingError: pickle data was truncated

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/test.py", line 261, in <module>
    main()
  File "./tools/test.py", line 190, in main
    dataset = build_dataset(cfg.data.test)
  File "/home/jarvis/coding/pyhome/github.com/meua/mmdetection3d/mmdet3d/datasets/builder.py", line 41, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
_pickle.UnpicklingError: NuScenesE2EDataset: pickle data was truncated
/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 70524) of binary: /home/jarvis/anaconda3/envs/uniad38/bin/python
Traceback (most recent call last):
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
         ./tools/test.py FAILED        
=======================================
Root Cause:
[0]:
  time: 2023-07-05_13:50:17
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 70524)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
  <NO_OTHER_FAILURES>
***************************************

(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$
```

**Comment by meua** [comment]
As shown below is my environment configuration:
```bash
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ nvidia-smi
Wed Jul  5 13:41:15 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.199.02   Driver Version: 470.199.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| 30%   40C    P8    15W / 350W |      1MiB / 12045MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ 
```

**Comment by 86kkd** [comment]
it is because that your data installed is broken i meet this error today and fixed it by reinstall them
wget https://github.com/OpenDriveLab/UniAD/releases/download/v1.0/nuscenes_infos_temporal_train.pkl  # train_infos
wget https://github.com/OpenDriveLab/UniAD/releases/download/v1.0/nuscenes_infos_temporal_val.pkl  # val_infos

**Comment by meua** [comment]
> it is because that your data installed is broken i meet this error today and fixed it by reinstall them wget https://github.com/OpenDriveLab/UniAD/releases/download/v1.0/nuscenes_infos_temporal_train.pkl # train_infos wget https://github.com/OpenDriveLab/UniAD/releases/download/v1.0/nuscenes_infos_temporal_val.pkl # val_infos

Okay, thanks a lot, I'll try it.

**Comment by zacharyzhang95** [comment]
I had the same problem when I was running the e2e test with one GPU (2080Ti with 22GB memory) by running the command:
```
./tools/uniad_dist_eval.sh ./projects/configs/stage2_e2e/base_e2e.py ./ckpts/uniad_base_e2e.pth 1
``` 
The log is shown below:

```
[                                                  ] 0/6019, elapsed: 0s, ETA:Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/multiprocessing/spawn.py", line 127, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
from_parent: <_io.BufferedReader name=56>
/home/zc/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 8512) of binary: /home/zc/anaconda3/envs/uniad/bin/python
Traceback (most recent call last):
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zc/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
./tools/test.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-15_15:37:52
  host      : rrg517
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 8512)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 8512
=====================================================
from_parent: <_io.BufferedReader name=52>
/home/zc/anaconda3/envs/uniad/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 14 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
``` 

I solved it with the following changes: Change 'workers_per_gpu=1' in config files **_base_e2e.py,_ _base_track_map.py_** and **_nus-3d.py_.** These files can be found in UniAD/projects/configs
