### ISSUE TITLE
AssertionError: Database version not found: data/nuscenes/v1.0-trainval

### ISSUE THREAD

**Issue by meua** [OpenDriveLab/UniAD#56]
```bash
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ ./tools/uniad_dist_eval.sh ./projects/configs/stage1_track_map/base_track_map.py ./ckpts/uniad_base_track_map.pth 1
projects.mmdet3d_plugin
Traceback (most recent call last):
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/jarvis/coding/pyhome/github.com/meua/UniAD/projects/mmdet3d_plugin/datasets/nuscenes_e2e_dataset.py", line 93, in __init__
    self.nusc = NuScenes(version=self.version,
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 62, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: data/nuscenes/v1.0-trainval

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/test.py", line 261, in <module>
    main()
  File "./tools/test.py", line 190, in main
    dataset = build_dataset(cfg.data.test)
  File "/home/jarvis/coding/pyhome/github.com/meua/mmdetection3d/mmdet3d/datasets/builder.py", line 41, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: NuScenesE2EDataset: Database version not found: data/nuscenes/v1.0-trainval
/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 90698) of binary: /home/jarvis/anaconda3/envs/uniad38/bin/python
Traceback (most recent call last):
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
         ./tools/test.py FAILED        
=======================================
Root Cause:
[0]:
  time: 2023-07-06_18:11:29
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 90698)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
  <NO_OTHER_FAILURES>
***************************************

(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ 

```

**Comment by meua** [comment]
The directory is wrong, it should be modified: v1.0-trainval-meta > v1.0-trainval
