### ISSUE TITLE
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 95119) of binary: /home/jarvis/anaconda3/envs/uniad38/bin/python

### ISSUE THREAD

**Issue by meua** [OpenDriveLab/UniAD#57]
```bash
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ ./tools/uniad_dist_eval.sh ./projects/configs/stage1_track_map/base_track_map.py ./path/to/ckpts.pth 1
projects.mmdet3d_plugin
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 42.824 seconds.
======
Reverse indexing ...
Done reverse indexing in 3.6 seconds.
======
load checkpoint from local path: ./path/to/ckpts.pth
Traceback (most recent call last):
  File "./tools/test.py", line 261, in <module>
    main()
  File "./tools/test.py", line 206, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 531, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 470, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 249, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 265, in load_from_local
    raise IOError(f'{filename} is not a checkpoint file')
OSError: ./path/to/ckpts.pth is not a checkpoint file
/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 95119) of binary: /home/jarvis/anaconda3/envs/uniad38/bin/python
Traceback (most recent call last):
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
         ./tools/test.py FAILED        
=======================================
Root Cause:
[0]:
  time: 2023-07-06_21:02:42
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 95119)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
  <NO_OTHER_FAILURES>
***************************************

(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ 

```

**Comment by YTEP-ZHI** [comment]
@meua `OSError: ./path/to/ckpts.pth is not a checkpoint file`
As is said here, you should change the `./path/to/ckpts.pth` in the command to the real path of the checkpoint.
