### ISSUE TITLE
Visualization Error

### ISSUE THREAD

**Issue by meua** [OpenDriveLab/UniAD#64]
```bash
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ ./tools/uniad_vis_result.sh
======
Loading NuScenes tables for version v1.0-mini...
25 category,
12 attribute,
4 visibility,
911 instance,
6 sensor,
50 calibrated_sensor,
650 ego_pose,
44 log,
10 scene,
50 sample,
650 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.197 seconds.
======
Reverse indexing ...
Traceback (most recent call last):
  File "./tools/analysis_tools/visualize/run.py", line 340, in <module>
    main(args)
  File "./tools/analysis_tools/visualize/run.py", line 302, in main
    viser = Visualizer(version='v1.0-mini', predroot=args.predroot, dataroot='data/nuscenes', **render_cfg)
  File "./tools/analysis_tools/visualize/run.py", line 46, in __init__
    self.nusc = NuScenes(version=version, dataroot=dataroot, verbose=True)
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 124, in __init__
    self.__make_reverse_index__(verbose)
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 171, in __make_reverse_index__
    record['category_name'] = self.get('category', inst['category_token'])['name']
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 216, in get
    return getattr(self, table_name)[self.getind(table_name, token)]
  File "/home/jarvis/anaconda3/envs/uniad38/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 225, in getind
    return self._token2ind[table_name][token]
KeyError: 'bb867e2064014279863c71a29b1eb381'
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ 
```

The content of the file uniad_vis_result.sh  is as follows:
```bash
#!/bin/bash

python ./tools/analysis_tools/visualize/run.py \
    --predroot ./data/infos/nuscenes_infos_temporal_val.pkl \
    --out_folder ./data/visualize/output \
    --demo_video ./data/video/test.mp4 \
    --project_to_cam True
```

**Comment by Yihanhu** [comment]
It seems like something wrong with you Nusc Dataset, did you put Nuscenes dataset under 'data/nuscenes' ?

**Comment by meua** [comment]
> It seems something wrong with you Nusc Dataset, did you put Nuscenes dataset under 'data/nuscenes' ?

I have put the data set in such a directory.

**Comment by meua** [comment]
> It seems something wrong with you Nusc Dataset, did you put Nuscenes dataset under 'data/nuscenes' ?

 Does it also require a full amount of nuScenes V1.0 full dataset data？

**Comment by meua** [comment]
> It seems something wrong with you Nusc Dataset, did you put Nuscenes dataset under 'data/nuscenes' ?

I downloaded the full dataset (nuscenes Full dataset (v1.0)), but this problem persists.

**Comment by meua** [comment]
@Yihanhu  Thanks, to solve this problem need to download the nuscenes  Mini dataset.
![image](https://github.com/OpenDriveLab/UniAD/assets/11570442/5634dd64-2719-4bcb-ae00-915901457f62)
