### ISSUE TITLE
KeyError: 'traj'

### ISSUE THREAD

**Issue by meua** [OpenDriveLab/UniAD#71]
Hello, I encountered the following error when executing the visualization command:
```bash
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ ./tools/uniad_vis_result.sh
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 18.497 seconds.
======
Reverse indexing ...
Done reverse indexing in 3.7 seconds.
======
Traceback (most recent call last):
  File "./tools/analysis_tools/visualize/run.py", line 340, in <module>
    main(args)
  File "./tools/analysis_tools/visualize/run.py", line 302, in main
    viser = Visualizer(version='v1.0-trainval', predroot=args.predroot, dataroot='data/nuscenes', **render_cfg)
  File "./tools/analysis_tools/visualize/run.py", line 62, in __init__
    self.predictions = self._parse_predictions_multitask_pkl(predroot)
  File "./tools/analysis_tools/visualize/run.py", line 111, in _parse_predictions_multitask_pkl
    trajs = outputs[k][f'traj'].numpy()
KeyError: 'traj'
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ 

```
The contents of the ./tools/uniad_vis_result.sh file are as follows:
```bash
#!/bin/bash

python ./tools/analysis_tools/visualize/run.py \
    --predroot ./output/results.pkl \
    --out_folder ./data/visualize/output \
    --demo_video ./data/video/test.mp4 \
    --project_to_cam True
```

**Comment by beyondpzk** [comment]
same question +1. 

I have got the results.pkl correctly, the logs is following:

![image](https://github.com/OpenDriveLab/UniAD/assets/35320670/90d80c8d-d566-4224-9ade-7fe5070128c3)


![image](https://github.com/OpenDriveLab/UniAD/assets/35320670/79987659-7fe3-422d-9fa6-b2389ec06003)


![image](https://github.com/OpenDriveLab/UniAD/assets/35320670/3b7b3c61-c368-430d-9697-be4b8d31e03a)

![image](https://github.com/OpenDriveLab/UniAD/assets/35320670/5374b352-f201-4ac4-a977-612c56fec48d)


but when I run the ./tools/uniad_vis_result.sh I also got "KeyError `traj`"

And I found no "traj" in results.pkl. 

![image](https://github.com/OpenDriveLab/UniAD/assets/35320670/a6958a30-2245-4736-b617-44520effb7a1)

**Comment by meua** [comment]
> same question +1.
> 
> I have got the results.pkl correctly, the logs is following:
> 
> ![image](https://user-images.githubusercontent.com/35320670/252833774-90d80c8d-d566-4224-9ade-7fe5070128c3.png)
> 
> ![image](https://user-images.githubusercontent.com/35320670/252833598-79987659-7fe3-422d-9fa6-b2389ec06003.png)
> 
> ![image](https://user-images.githubusercontent.com/35320670/252833653-3b7b3c61-c368-430d-9697-be4b8d31e03a.png)
> 
> ![image](https://user-images.githubusercontent.com/35320670/252833823-5374b352-f201-4ac4-a977-612c56fec48d.png)
> 
> but when I run the ./tools/uniad_vis_result.sh I also got "KeyError `traj`"
> 
> And I found no "traj" in results.pkl.
> 
> ![image](https://user-images.githubusercontent.com/35320670/252834300-a6958a30-2245-4736-b617-44520effb7a1.png)

Please tell me if you solve it, thank you.

**Comment by beyondpzk** [comment]
I got following result jpgs 

![image](https://github.com/OpenDriveLab/UniAD/assets/35320670/93d0e5aa-3ae6-43cf-a135-c68bdbe7489c)

**Comment by ilnehc** [comment]
@meua @beyondpzk This seems a bug from inconsistent results saving in the test process. We are looking into this issue.

**Comment by meua** [comment]
> @meua @beyondpzk This is a bug from inconsistent results saving in the test process, when you visualize outputs from stage 1 only. You need the full results (stage 2). See [#39 (comment)](https://github.com/OpenDriveLab/UniAD/issues/39#issuecomment-1617641348). We will fix it.

Thank you very much, I finally output the visualization information through 2e2.
`./tools/uniad_dist_eval.sh ./projects/configs/stage2_e2e/base_e2e.py ./ckpts/uniad_base_e2e.pth 1 && python ./tools/analysis_tools/visualize/run.py --predroot ./output/results.pkl --out_folder ./output_visualize --demo_video test_demo.avi --project_to_cam True`

**Comment by ZhoubinXM** [comment]
> ./tools/uniad_dist_eval.sh ./projects/configs/stage2_e2e/base_e2e.py ./ckpts/uniad_base_e2e.pth 1 && python ./tools/analysis_tools/visualize/run.py --predroot ./output/results.pkl --out_folder ./output_visualize --demo_video test_demo.avi --project_to_cam True

If you want to get visualization results, before end-to-end training or eval, you can check the run.py script and comment out the code about traj, you can get pv and bev images of det, like:
![image](https://github.com/OpenDriveLab/UniAD/assets/44090409/3970304c-4089-46f1-8d1b-1da8d5daddac)

**Comment by meua** [comment]
> > ./tools/uniad_dist_eval.sh ./projects/configs/stage2_e2e/base_e2e.py ./ckpts/uniad_base_e2e.pth 1 && python ./tools/analysis_tools/visualize/run.py --predroot ./output/results.pkl --out_folder ./output_visualize --demo_video test_demo.avi --project_to_cam True
> 
> If you want to get visualization results, before end-to-end training or eval, you can check the run.py script and comment out the code about traj, you can get pv and bev images of det, like: ![image](https://user-images.githubusercontent.com/44090409/254757053-3970304c-4089-46f1-8d1b-1da8d5daddac.png)

Okay, thank you very much for your input, I will try it soon.

**Comment by doublemanyu** [comment]
> same question +1.
> 
> I have got the results.pkl correctly, the logs is following:
> 
> ![image](https://github.com/OpenDriveLab/UniAD/assets/35320670/90d80c8d-d566-4224-9ade-7fe5070128c3)
> 
> ![image](https://github.com/OpenDriveLab/UniAD/assets/35320670/79987659-7fe3-422d-9fa6-b2389ec06003)
> 
> ![image](https://github.com/OpenDriveLab/UniAD/assets/35320670/3b7b3c61-c368-430d-9697-be4b8d31e03a)
> 
> ![image](https://github.com/OpenDriveLab/UniAD/assets/35320670/5374b352-f201-4ac4-a977-612c56fec48d)
> 
> but when I run the ./tools/uniad_vis_result.sh I also got "KeyError `traj`"
> 
> And I found no "traj" in results.pkl.
> 
> ![image](https://github.com/OpenDriveLab/UniAD/assets/35320670/a6958a30-2245-4736-b617-44520effb7a1)

Hi, there. How to get results.pkl?
