### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/nuscenes/samples/CAM_FRONT/n008-2018-08-31-11-19-57-0400__CAM_FRONT__1535729312412404.jpg'

### ISSUE THREAD

**Issue by yudefu** [OpenDriveLab/UniAD#75]
Hello: I have downloaded v1.0 trainval06_ Blobs, but I encountered the error mentioned above during training. I would like to ask if the training dataset is full_ There is too much download space for dataset (v1.0), how can I solve it better？

**Comment by YTEP-ZHI** [comment]
@yudefu Hi, you have to download the full dataset (all blobs) to start conducting experiments .

**Comment by yudefu** [comment]
> @yudefu Hi, you have to download the full dataset (all blobs) to start conducting experiments .

Excuse me, I encountered the following error during training. I would like to ask where is num_workers set? My local disk has 36T；

**Comment by yudefu** [comment]
> @yudefu Hi, you have to download the full dataset (all blobs) to start conducting experiments .
Excuse me, I encountered the following error during training. I would like to ask where is num_workers set? My local disk has 36T；

ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/queues.py", line 245, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/local/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/corex/lib64/python3/dist-packages/torch/multiprocessing/reductions.py", line 366, in reduce_storage
    fd, size = storage._share_fd_cpu_()
RuntimeError: unable to write to file </torch_27049_535114776_55>: No space left on device (28)
Traceback (most recent call last):
  File "/home/work/yudefu/UniAD/./tools/train.py", line 257, in <module>
    main()
  File "/home/work/yudefu/UniAD/./tools/train.py", line 245, in main
    custom_train_model(
  File "/home/work/yudefu/UniAD/projects/mmdet3d_plugin/uniad/apis/train.py", line 21, in custom_train_model
    custom_train_detector(
  File "/home/work/yudefu/UniAD/projects/mmdet3d_plugin/uniad/apis/mmdet_train.py", line 194, in custom_train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 130, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/usr/local/corex/lib64/python3/dist-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/usr/local/corex/lib64/python3/dist-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/usr/local/corex/lib64/python3/dist-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/usr/local/corex/lib64/python3/dist-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/corex/lib64/python3/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/corex/lib64/python3/dist-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.9/site-packages/mmcv/parallel/collate.py", line 79, in collate
    return {
  File "/usr/local/lib/python3.9/site-packages/mmcv/parallel/collate.py", line 80, in <dictcomp>
    key: collate([d[key] for d in batch], samples_per_gpu)
  File "/usr/local/lib/python3.9/site-packages/mmcv/parallel/collate.py", line 59, in collate
    stacked.append(default_collate(padded_samples))
  File "/usr/local/corex/lib64/python3/dist-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/usr/local/corex/lib64/python3/dist-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/usr/local/corex/lib64/python3/dist-packages/torch/utils/data/_utils/collate.py", line 161, in collate_tensor_fn
    storage = elem.storage()._new_shared(numel, device=elem.device)
  File "/usr/local/corex/lib64/python3/dist-packages/torch/storage.py", line 635, in _new_shared
    untyped_storage = torch.UntypedStorage._new_shared(size * self.element_size(), device=device)
  File "/usr/local/corex/lib64/python3/dist-packages/torch/storage.py", line 223, in _new_shared
    return cls._new_using_fd_cpu(size)
RuntimeError: unable to write to file </torch_26731_4127955964_0>: No space left on device (28)

Traceback (most recent call last):
  File "/home/work/yudefu/UniAD/./tools/train.py", line 257, in <module>
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).

**Comment by YTEP-ZHI** [comment]
> "RuntimeError: unable to write to file </torch_26731_4127955964_0>: No space left on device (28)" 

As is shown, there's no available space on your device, thus the program cannot write or save anything.

**Comment by yudefu** [comment]
> > "RuntimeError: unable to write to file </torch_26731_4127955964_0>: No space left on device (28)"
> 
> As is shown, there's no available space on your device, thus the program cannot write or save anything.

Hmm, thanks for the reply! I increased the shared memory in the morning, and I can run. Our own graphics card has 32g memory (our company is Tianshu Zhixin). I used 12 full card resources, but I still reported that the cuda memory is not enough; I would like to ask for advice : Did you use 8 A100s, each with 50g of memory? I plan to gradually reduce the parameter queue_length and try to use 16 full cards. Do you have other strategies for optimizing memory? I'm afraid that the 16 graphics cards on my side will not be able to run.

**Comment by YTEP-ZHI** [comment]
@yudefu As is said in the doc: https://github.com/OpenDriveLab/UniAD/blob/main/docs/TRAIN_EVAL.md#gpu-requirements-:
The first-stage training takes ~ 50 GB GPU memory per gpu, ~ 2 days for 6 epochs on 8 A100 GPUs.

HINT: To save GPU memory, you can change queue_length=5 to 3 which will slightly degrade the tracking performance. Then the training would take ~30 GB GPU memory and is affordable for V100 GPUs (32GB version).

The second-stage training takes ~ 17 GB GPU memory per gpu, ~ 4 days for 20 epochs on 8 A100 GPUs.

NOTE: Compared to the first-stage, much less GPU memory is required because we freeze the BEV encoder in this stage to focus on learning task-specific queries. Due to this, you can run the second-stage training on V100 or 3090 devices.
