### ISSUE TITLE
How to use v1.0-mini dataset.

### ISSUE THREAD

**Issue by GenoWong** [OpenDriveLab/UniAD#86]
Nice work!!! My PC doestn't have enough memory, I tried to modified the default dataset, but still has below error.
![image](https://github.com/OpenDriveLab/UniAD/assets/72009672/a3f748ca-8b41-4ac2-9aa6-6a5bf35ebc60)

So Can you tell me how to use v1.0-mini dataset.
Thank you！！！

**Comment by TonyPeng-2018** [comment]
Same Question.

**Comment by TonyPeng-2018** [comment]
@GenoWong In the create_data.py, you can use version to change the dataset you wanna use.

**Comment by yudefu** [comment]
> Same Question.

你好，你跑成功训练stage1或者测试那个例子了吗

**Comment by lzf18** [comment]
准备数据的时候，把UniAD/tools/uniad_create_data.sh脚本里边的--version参数改成v1.0-mini，生成相应的nuscenes_infos_temporal_{train/val}.pkl文件之后再用评估脚本

**Comment by yudefu** [comment]
> 准备数据的时候，把UniAD/tools/uniad_create_data.sh脚本里边的--version参数改成v1.0-mini，生成相应的nuscenes_infos_temporal_{train/val}.pkl文件之后再用评估脚本

你好，你的意思是不能直接运行：./tools/uniad_dist_eval.sh ./projects/configs/stage1_track_map/base_track_map.py ./ckpts/uniad_base_track_map.pth NUM_GPUS
我上周跑的最后的结果不对，请教你一下，是不是按照你说的操作就可以解决啦：
Aggregated results:
AMOTA 0.000
AMOTP 2.000
RECALL 0.000
MOTAR 0.000
GT 14556
MOTA 0.000
MOTP 2.000
MT 0
ML 6470
FAF 500.0
TP 0
FP 0
FN 101897
IDS 0
FRAG 0
TID 20.00
LGD 20.00

**Comment by lzf18** [comment]
> 

是的，先运行uniad_create_data.sh脚本，然后运行uniad_dist_eval.sh脚本，我的结果如下：
Per-class results:
                AMOTA   AMOTP   RECALL  MOTAR   GT      MOTA    MOTP    MT      ML      FAF     TP      FP      FN      IDS FRAG     TID     LGD
bicycle         0.279   1.379   0.268   0.909   41      0.244   0.647   1       4       4.8     11      1       30      0   00.17    1.00
bus             0.657   1.134   0.788   0.885   33      0.697   0.845   0       0       9.1     26      3       7       0   10.00    3.00
car             0.661   0.835   0.761   0.759   2188    0.576   0.564   63      17      492.6   1659    399     523     6   11       1.56    1.75
motorcy         0.483   1.274   0.540   0.901   224     0.487   0.636   1       1       24.5    121     12      103     0   14.00    4.35
pedestr         0.424   1.095   0.475   0.900   1088    0.421   0.772   19      28      78.5    509     51      571     8   71.77    2.42
trailer         nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan nan      nan     nan
truck           0.775   0.938   0.800   1.000   95      0.800   0.634   3       1       0.0     76      0       19      0   01.33    1.67

Aggregated results:
AMOTA   0.544
AMOTP   1.140
RECALL  0.633
MOTAR   0.848
GT      611
MOTA    0.550
MOTP    0.703
MT      91
ML      49
FAF     106.3
TP      2530
FP      474
FN      1117
IDS     22
FRAG    22
TID     1.60
LGD     2.37

**Comment by yudefu** [comment]
> > 
> 
> 是的，先运行uniad_create_data.sh脚本，然后运行uniad_dist_eval.sh脚本，我的结果如下： Per-class results: AMOTA AMOTP RECALL MOTAR GT MOTA MOTP MT ML FAF TP FP FN IDS FRAG TID LGD bicycle 0.279 1.379 0.268 0.909 41 0.244 0.647 1 4 4.8 11 1 30 0 00.17 1.00 bus 0.657 1.134 0.788 0.885 33 0.697 0.845 0 0 9.1 26 3 7 0 10.00 3.00 car 0.661 0.835 0.761 0.759 2188 0.576 0.564 63 17 492.6 1659 399 523 6 11 1.56 1.75 motorcy 0.483 1.274 0.540 0.901 224 0.487 0.636 1 1 24.5 121 12 103 0 14.00 4.35 pedestr 0.424 1.095 0.475 0.900 1088 0.421 0.772 19 28 78.5 509 51 571 8 71.77 2.42 trailer nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan truck 0.775 0.938 0.800 1.000 95 0.800 0.634 3 1 0.0 76 0 19 0 01.33 1.67
> 
> Aggregated results: AMOTA 0.544 AMOTP 1.140 RECALL 0.633 MOTAR 0.848 GT 611 MOTA 0.550 MOTP 0.703 MT 91 ML 49 FAF 106.3 TP 2530 FP 474 FN 1117 IDS 22 FRAG 22 TID 1.60 LGD 2.37

你好，我再打扰你一下哈：我下载了v1.0-mini数据集，按照你说的eval了一下，结果看着不正常，可以帮忙看看吗？如果方便可以加一下wx：y1193547749（谢谢啦）
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 81/81, 0.6 task/s, elapsed: 130s, ETA:     0s
writing results to output/results.pkl
Start to convert detection format...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 81/81, 39.9 task/s, elapsed: 2s, ETA:     0s
Results writes to test/base_track_map/Tue_Aug__1_11_37_07_2023/results_nusc.json
Start to convert detection format...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 81/81, 13.3 task/s, elapsed: 6s, ETA:     0s
Results writes to test/base_track_map/Tue_Aug__1_11_37_07_2023/results_nusc_det.json
Initializing nuScenes detection evaluation
Loaded results from test/base_track_map/Tue_Aug__1_11_37_07_2023/results_nusc_det.json. Found detections for 81 samples.
Loading annotations for mini_val split from nuScenes version: v1.0-mini
100%|██████████| 81/81 [00:00<00:00, 197.91it/s]
Loaded ground truth annotations for 81 samples.
Filtering predictions
=> Original number of boxes: 9396
=> After distance based filtering: 9394
=> After LIDAR and RADAR points based filtering: 9394
=> After bike rack filtering: 9317
Filtering ground truth annotations
=> Original number of boxes: 4441
=> After distance based filtering: 3785
=> After LIDAR and RADAR points based filtering: 3393
=> After bike rack filtering: 3393
Accumulating metric data...
Calculating metrics...
Saving metrics to: test/base_track_map/Tue_Aug__1_11_37_07_2023/det
mAP: 0.3560
mATE: 0.7420
mASE: 0.4686
mAOE: 0.6335
mAVE: 0.6055
mAAE: 0.2941
NDS: 0.4036
Eval time: 6.1s

Per-class results:
Object Class    AP      ATE     ASE     AOE     AVE     AAE
car     0.619   0.504   0.159   0.114   0.118   0.089
truck   0.468   0.745   0.177   0.068   0.070   0.001
bus     0.465   0.846   0.151   0.322   1.808   0.064
trailer 0.000   1.000   1.000   1.000   1.000   1.000
construction_vehicle    0.000   1.000   1.000   1.000   1.000   1.000
pedestrian      0.552   0.644   0.253   0.406   0.266   0.200
motorcycle      0.455   0.685   0.318   0.985   0.056   0.000
bicycle 0.388   0.614   0.240   0.806   0.527   0.000
traffic_cone    0.611   0.383   0.389   nan     nan     nan
barrier 0.000   1.000   1.000   1.000   nan     nan
======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 1.256 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.2 seconds.
======
Initializing nuScenes tracking evaluation
Loaded results from test/base_track_map/Tue_Aug__1_11_37_07_2023/results_nusc.json. Found detections for 81 samples.
Loading annotations for mini_val split from nuScenes version: v1.0-mini
100%|██████████| 81/81 [00:00<00:00, 129.10it/s]
Loaded ground truth annotations for 81 samples.
Filtering tracks
=> Original number of boxes: 2868
=> After distance based filtering: 2868
=> After LIDAR and RADAR points based filtering: 2868
=> After bike rack filtering: 2848
Filtering ground truth tracks
=> Original number of boxes: 4402
=> After distance based filtering: 3748
=> After LIDAR and RADAR points based filtering: 3358
=> After bike rack filtering: 3358
Accumulating metric data...
Computing metrics for class bicycle...

Computed thresholds

                MOTAR   MOTP    Recall  Frames  GT      GT-Mtch GT-Miss GT-IDS  Pred    Pred-TP Pred-FP Pred-IDS
thr_0.4821      0.000   0.641   0.415   21      41      5       24      12      23      5       6       12

                MOTAR   MOTP    Recall  Frames  GT      GT-Mtch GT-Miss GT-IDS  Pred    Pred-TP Pred-FP Pred-IDS
thr_0.5582      0.000   0.665   0.390   21      41      5       25      11      21      5       5       11

                MOTAR   MOTP    Recall  Frames  GT      GT-Mtch GT-Miss GT-IDS  Pred    Pred-TP Pred-FP Pred-IDS
thr_0.6385      0.500   0.562   0.341   21      41      4       27      10      16      4       2       10

Computing metrics for class bus...

Computed thresholds

Computing metrics for class car...

Computed thresholds

Computing metrics for class motorcycle...

Computed thresholds

Computing metrics for class pedestrian...

Computed thresholds

Computing metrics for class trailer...

Computing metrics for class truck...

Computed thresholds

Calculating metrics...
Saving metrics to: test/base_track_map/Tue_Aug__1_11_37_07_2023/track

### Final results ###

Per-class results:
                AMOTA   AMOTP   RECALL  MOTAR   GT      MOTA    MOTP    MT      ML      FAF     TP      FP      FN      IDS     FRAG    TID     LGD
bicycle         0.013   1.897   0.341   0.500   41      0.049   0.562   1       3       9.5     4       2       27      10      3       0.38    1.62
bus             0.000   2.000   0.000   0.000   33      0.000   2.000   0       1       500.0   0       nan     33      nan     nan     20.00   20.00
car             0.000   2.000   0.000   0.000   2188    0.000   2.000   0       114     500.0   0       nan     2188    nan     nan     20.00   20.00
motorcy         0.000   2.000   0.000   0.000   224     0.000   2.000   0       10      500.0   0       nan     224     nan     nan     20.00   20.00
pedestr         0.000   2.000   0.000   0.000   1088    0.000   2.000   0       67      500.0   0       nan     1088    nan     nan     20.00   20.00
trailer         nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan
truck           0.000   2.000   0.000   0.000   95      0.000   2.000   0       4       500.0   0       nan     95      nan     nan     20.00   20.00

Aggregated results:
AMOTA   0.002
AMOTP   1.983
RECALL  0.057
MOTAR   0.083
GT      611
MOTA    0.008
MOTP    1.760
MT      1
ML      199
FAF     418.3
TP      4
FP      2
FN      3655
IDS     10
FRAG    3
TID     16.73
LGD     16.94
Eval time: 3.9s

**Comment by Siriusbz** [comment]
你好，我使用uniad_create_data.sh，修改了version=v1.0-mini，创建了两个.pkl文件，但是在测试阶段发现报错，data/nuscenes/./data/nuscenes/samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151603512404.jpg ，第一个data/nuscenes来自base_track_map.py中的data_root，不知道为什么会报这样的错，我运行full的时候，用提供的.pkl就没有问题

**Comment by yudefu** [comment]
> 你好，我使用uniad_create_data.sh，修改了version=v1.0-mini，创建了两个.pkl文件，但是在测试阶段发现报错，data/nuscenes/./data/nuscenes/samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151603512404.jpg ，第一个data/nuscenes来自base_track_map.py中的data_root，不知道为什么会报这样的错，我运行full的时候，用提供的.pkl就没有问题

问问题可以把错误信息贴出来，你这个错误是因为报错信息代码里面有一个join操作，给它注释掉就可以了

**Comment by zhangzhongzhong1** [comment]
File "./tools/test.py", line 261, in <module>
    main()
  File "./tools/test.py", line 231, in main
    outputs = custom_multi_gpu_test(model, data_loader, args.tmpdir,
  File "/home/zzz/Downloads/UniAD-1.0.1/projects/mmdet3d_plugin/uniad/apis/test.py", line 88, in custom_multi_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/zzz/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/zzz/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/zzz/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/zzz/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zzz/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zzz/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zzz/anaconda3/envs/uniad/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zzz/Downloads/UniAD-1.0.1/projects/mmdet3d_plugin/datasets/nuscenes_e2e_dataset.py", line 726, in __getitem__
    return self.prepare_test_data(idx)
  File "/home/zzz/Downloads/UniAD-1.0.1/projects/mmdet3d_plugin/datasets/nuscenes_e2e_dataset.py", line 254, in prepare_test_data
    example = self.pipeline(input_dict)
  File "/home/zzz/anaconda3/envs/uniad/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/zzz/Downloads/UniAD-1.0.1/projects/mmdet3d_plugin/datasets/pipelines/loading.py", line 53, in __call__
    img = mmcv.imread(img_path, self.color_type)
  File "/home/zzz/anaconda3/envs/uniad/lib/python3.8/site-packages/mmcv/image/io.py", line 176, in imread
    check_file_exist(img_or_path,
  File "/home/zzz/anaconda3/envs/uniad/lib/python3.8/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: img file does not exist: data/nuscenes/v1.0-mini/./data/nuscenes/v1.0-mini/samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151603512404.jpg
你好，这个问题能帮忙看一下吗
